#Check send_mail() function for Filename when merging the project
from tkinter import*
from tkinter import ttk
import csv,os
def exit():
    root.destroy()
def compare():
    root.destroy()
    os.system("Compare.py")
def one_shot():
    root.destroy()
    os.system("One_Shot.py")
# def faq():
#     root.destroy()
#     os.system("FAQ.py")
root = Tk()
root.resizable(0,0)
root.wm_attributes('-transparentcolor','grey')
root.geometry('720x480')
root.title("Home")
s = ttk.Style()
s.configure('my.TButton', font=("Roboto", 16))
panel = Label(root)
# panel.configure(text='''Label''')
panel.place(x=0,y=0)
bg = PhotoImage(file = "./Assests/bg.png")
label = Label( root, image = bg)
label.place(x = -2, y = 0)
label = ttk.Label(root, text=" Batch A-05 ")
label.configure(font=("Roboto", 20, "bold"))
label.pack()
label = ttk.Label(root, text="\nGait Recognition using One Shot Learning")
label.configure(font=("Roboto", 20, "bold"))
label.pack()
label = ttk.Label(root, text="Please choose one of the following\n\n")
label.configure(font=("Roboto", 16, "bold"))
label.pack()
# Button(root, text="1. Validate the data",font=("Roboto", 12),command=validate).place(x=290,y=210)
button = ttk.Button(root, text=" One Shot Learning ",style='my.TButton',command=one_shot)
button.pack()
label = ttk.Label(root, text="")
label.pack()
button = ttk.Button(root, text=" Comparision Gait Recognition with other methods ",style='my.TButton',command=compare)
button.pack()
label = ttk.Label(root, text="")
label.pack()
button = ttk.Button(root, text=" Exit ",style='my.TButton',command=exit)
button.pack()
root.mainloop()