from tkinter import *
from tkinter import ttk
import subprocess,os
from turtle import position
from PIL import ImageTk, Image
from tkinter import filedialog
def choice():
    print("\nHidden Button Clicked! Might take a while...")
    one_shot_output = subprocess.run(['python','../One Shot/main.py'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    # one_shot_output = subprocess.run(['python','sub.py'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    text.insert(INSERT,one_shot_output)
    text.see(END)
    text.update_idletasks()
def dis_acc():
    one_shot_output = subprocess.run(['python','../One Shot/dis_acc.py'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    text.insert(INSERT,one_shot_output)
    text.see(END)
    text.update_idletasks()
def find_gait():
    filename = filedialog.askopenfilename()
    one_shot_output = subprocess.run(['python','../One Shot/Find.py',filename], stdout=subprocess.PIPE).stdout.decode('utf-8')
    # one_shot_output = subprocess.run(['python','sub.py'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    text.insert(INSERT,one_shot_output)
    text.see(END)
    text.update_idletasks()
def Go_Home():
    root.destroy()
    os.system("main.py")
root = Tk()
root.resizable(0,0)
root.wm_attributes('-transparentcolor','grey')
root.update_idletasks()
root.geometry('720x480')
root.title("One Shot Learning")
s = ttk.Style()
s.configure('my.TButton', font=("Roboto", 16))
bg = PhotoImage(file = "./Assests/bg.png")
label = Label( root, image = bg)
label.place(x = -2, y = 0)
text=Text(root,height=15,width=70)
scroll=Scrollbar(text)
home = ttk.Button(root,command=Go_Home)
home_img = ImageTk.PhotoImage(Image.open("Assests/Home_Button.jpg").resize((35, 35)))
home.configure(image=home_img)
home.configure(text='''Home''')
home.place(x=650,y=55)
home = Button(root,command=choice,highlightthickness = 0, bd = 0)
hidden_img = ImageTk.PhotoImage(Image.open("Assests/Hidden_Button.png").resize((35, 35)))
home.configure(image=hidden_img)
home.configure(text='''Actual''')
home.place(x=650,y=105)
label = ttk.Label(root, text=" One Shot Learning ",font=("Roboto", 20,"bold"))
label.pack()
label = ttk.Label(root, text="")
label.pack()
button = ttk.Button(root,text="Display Accuracy",width=50,command=dis_acc)
button.pack()
label = ttk.Label(root, text="")
label.pack()
button = ttk.Button(root,text="Recognize person from Gait Enery Image",width=50,command=find_gait)
button.pack()
label = Label(root, text="")
label.pack()
text.configure(yscrollcommand=scroll.set)
text.config(font="Roboto")
text.pack()
root.mainloop()