from tkinter import *
import subprocess
def choice():
    one_shot_output = subprocess.run(['python','../Neural Network/main.py'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    # one_shot_output = subprocess.run(['python','sub.py'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    text.insert(INSERT,one_shot_output)
    text.see(END)
    text.update_idletasks()
root = Tk()
root.resizable(0,0)
root.wm_attributes('-transparentcolor','grey')
root.update_idletasks()
root.geometry('720x480')
root.title("One Shot Learning")
text=Text(root,height=30,width=90)
scroll=Scrollbar(text)
label = Label(root, text="One Shot Learning",font=("Roboto", 25,"bold"))
label.pack()
button = Button(root,text="Choose a Gait Energy Image for Recognition",command=choice)
button.pack()
text.configure(yscrollcommand=scroll.set)
text.config(font="Roboto")
text.pack()
root.mainloop()